variables: 
    ## Add this under variables section in the pipeline
    azureSubscription: 83b49447-1296-4e78-847c-baaebb505b88
    appName: invt-1578939256727

## Add the below snippet at the end of your pipeline
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: webAppLinux
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
