trigger:
- master

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: 83b49447-1296-4e78-847c-baaebb505b88
  appName: invt-1578939256727
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

- task: AzureWebApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: <Azure service connection>
    appType: webAppLinux
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
